AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 4.0

Layout/EndOfLine:
  EnforcedStyle: lf

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes